//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmj.WebApp.SendSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mms.wemediacn.com/", ConfigurationName="SendSMS.SMSServiceSoap")]
    public interface SMSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMS(string mobile, int FormatID, string Content, System.DateTime ScheduleDate, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/SendBatchSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendBatchSMS(string mobileList, int FormatID, string Content, System.DateTime deadLineTime, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/SendSMSCovey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSCovey(string XMLStr, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/QuerySMSState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement QuerySMSState(string MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/QuerySmsSendRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement QuerySmsSendRecord(System.DateTime time, int MinID, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/CanelSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CanelSMS(string MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/QuerySMSUP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement QuerySMSUP(int MinID, int Count, string TokenID, string externCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/QuerySmsSeqReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement QuerySmsSeqReport(int MinID, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/TestTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestTemplate(int templateId, string paramType, string paramData, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mms.wemediacn.com/SendTemplateSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendTemplateSMS(string mobile, int FormatID, int templateId, string paramType, string paramData, string TokenID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceSoapChannel : Hmj.WebApp.SendSMS.SMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<Hmj.WebApp.SendSMS.SMSServiceSoap>, Hmj.WebApp.SendSMS.SMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendSMS(string mobile, int FormatID, string Content, System.DateTime ScheduleDate, string TokenID) {
            return base.Channel.SendSMS(mobile, FormatID, Content, ScheduleDate, TokenID);
        }
        
        public string SendBatchSMS(string mobileList, int FormatID, string Content, System.DateTime deadLineTime, string TokenID) {
            return base.Channel.SendBatchSMS(mobileList, FormatID, Content, deadLineTime, TokenID);
        }
        
        public string SendSMSCovey(string XMLStr, string TokenID) {
            return base.Channel.SendSMSCovey(XMLStr, TokenID);
        }
        
        public System.Xml.XmlElement QuerySMSState(string MessageID) {
            return base.Channel.QuerySMSState(MessageID);
        }
        
        public System.Xml.XmlElement QuerySmsSendRecord(System.DateTime time, int MinID, string TokenID) {
            return base.Channel.QuerySmsSendRecord(time, MinID, TokenID);
        }
        
        public string CanelSMS(string MessageID) {
            return base.Channel.CanelSMS(MessageID);
        }
        
        public System.Xml.XmlElement QuerySMSUP(int MinID, int Count, string TokenID, string externCode) {
            return base.Channel.QuerySMSUP(MinID, Count, TokenID, externCode);
        }
        
        public System.Xml.XmlElement QuerySmsSeqReport(int MinID, string TokenID) {
            return base.Channel.QuerySmsSeqReport(MinID, TokenID);
        }
        
        public string TestTemplate(int templateId, string paramType, string paramData, string TokenID) {
            return base.Channel.TestTemplate(templateId, paramType, paramData, TokenID);
        }
        
        public string SendTemplateSMS(string mobile, int FormatID, int templateId, string paramType, string paramData, string TokenID) {
            return base.Channel.SendTemplateSMS(mobile, FormatID, templateId, paramType, paramData, TokenID);
        }
    }
}
