//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmj.WebApp.OriginalXml {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wechat.beautyfarm.com.cn/", ConfigurationName="OriginalXml.beautyfarmWeChatServiceSoap")]
    public interface beautyfarmWeChatServiceSoap {
        
        // CODEGEN: 命名空间 http://wechat.beautyfarm.com.cn/ 的元素名称 strOriginalXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wechat.beautyfarm.com.cn/GetOriginalXml", ReplyAction="*")]
        Hmj.WebApp.OriginalXml.GetOriginalXmlResponse GetOriginalXml(Hmj.WebApp.OriginalXml.GetOriginalXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOriginalXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOriginalXml", Namespace="http://wechat.beautyfarm.com.cn/", Order=0)]
        public Hmj.WebApp.OriginalXml.GetOriginalXmlRequestBody Body;
        
        public GetOriginalXmlRequest() {
        }
        
        public GetOriginalXmlRequest(Hmj.WebApp.OriginalXml.GetOriginalXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wechat.beautyfarm.com.cn/")]
    public partial class GetOriginalXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strOriginalXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strSourceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMessage;
        
        public GetOriginalXmlRequestBody() {
        }
        
        public GetOriginalXmlRequestBody(string strOriginalXml, string strSourceCode, string strMessage) {
            this.strOriginalXml = strOriginalXml;
            this.strSourceCode = strSourceCode;
            this.strMessage = strMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOriginalXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOriginalXmlResponse", Namespace="http://wechat.beautyfarm.com.cn/", Order=0)]
        public Hmj.WebApp.OriginalXml.GetOriginalXmlResponseBody Body;
        
        public GetOriginalXmlResponse() {
        }
        
        public GetOriginalXmlResponse(Hmj.WebApp.OriginalXml.GetOriginalXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wechat.beautyfarm.com.cn/")]
    public partial class GetOriginalXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetOriginalXmlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strMessage;
        
        public GetOriginalXmlResponseBody() {
        }
        
        public GetOriginalXmlResponseBody(bool GetOriginalXmlResult, string strMessage) {
            this.GetOriginalXmlResult = GetOriginalXmlResult;
            this.strMessage = strMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface beautyfarmWeChatServiceSoapChannel : Hmj.WebApp.OriginalXml.beautyfarmWeChatServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class beautyfarmWeChatServiceSoapClient : System.ServiceModel.ClientBase<Hmj.WebApp.OriginalXml.beautyfarmWeChatServiceSoap>, Hmj.WebApp.OriginalXml.beautyfarmWeChatServiceSoap {
        
        public beautyfarmWeChatServiceSoapClient() {
        }
        
        public beautyfarmWeChatServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public beautyfarmWeChatServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public beautyfarmWeChatServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public beautyfarmWeChatServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hmj.WebApp.OriginalXml.GetOriginalXmlResponse Hmj.WebApp.OriginalXml.beautyfarmWeChatServiceSoap.GetOriginalXml(Hmj.WebApp.OriginalXml.GetOriginalXmlRequest request) {
            return base.Channel.GetOriginalXml(request);
        }
        
        public bool GetOriginalXml(string strOriginalXml, string strSourceCode, ref string strMessage) {
            Hmj.WebApp.OriginalXml.GetOriginalXmlRequest inValue = new Hmj.WebApp.OriginalXml.GetOriginalXmlRequest();
            inValue.Body = new Hmj.WebApp.OriginalXml.GetOriginalXmlRequestBody();
            inValue.Body.strOriginalXml = strOriginalXml;
            inValue.Body.strSourceCode = strSourceCode;
            inValue.Body.strMessage = strMessage;
            Hmj.WebApp.OriginalXml.GetOriginalXmlResponse retVal = ((Hmj.WebApp.OriginalXml.beautyfarmWeChatServiceSoap)(this)).GetOriginalXml(inValue);
            strMessage = retVal.Body.strMessage;
            return retVal.Body.GetOriginalXmlResult;
        }
    }
}
