//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmj.WebApp.DicountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="DicountService.ZWS_LOY_WELFARE")]
    public interface ZWS_LOY_WELFARE {
        
        // CODEGEN: 操作 Z_CRM_LOY_WELFARE 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_LOY_WELFARE:Z_CRM_LOY_WELFARERequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hmj.WebApp.DicountService.Z_CRM_LOY_WELFAREResponse1 Z_CRM_LOY_WELFARE(Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_LOY_WELFARE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_ZCPIDOField;
        
        private string iV_ZCPLOYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IV_ZCPIDO {
            get {
                return this.iV_ZCPIDOField;
            }
            set {
                this.iV_ZCPIDOField = value;
                this.RaisePropertyChanged("IV_ZCPIDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IV_ZCPLOY {
            get {
                return this.iV_ZCPLOYField;
            }
            set {
                this.iV_ZCPLOYField = value;
                this.RaisePropertyChanged("IV_ZCPLOY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_COUPON_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_LOY_WELFARE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zCPTYPEField;
        
        private string zCPTYPETField;
        
        private string zCPMATNRField;
        
        private string zCPNAMEField;
        
        private string zCPMSField;
        
        private string zCPIDOField;
        
        private string zCPSTATEField;
        
        private decimal zCPVALUEField;
        
        private string zCPSTAField;
        
        private string zCPENDField;
        
        private string zCPCHANNELField;
        
        private string zCPSTOREField;
        
        private string zWMATNRField;
        
        private string zCPSERNRField;
        
        private string zCPLOYField;
        
        private decimal zCPPRICEField;
        
        private string zCPSCENEField;
        
        private string zCPMULTICKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZCPTYPE {
            get {
                return this.zCPTYPEField;
            }
            set {
                this.zCPTYPEField = value;
                this.RaisePropertyChanged("ZCPTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZCPTYPET {
            get {
                return this.zCPTYPETField;
            }
            set {
                this.zCPTYPETField = value;
                this.RaisePropertyChanged("ZCPTYPET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZCPMATNR {
            get {
                return this.zCPMATNRField;
            }
            set {
                this.zCPMATNRField = value;
                this.RaisePropertyChanged("ZCPMATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZCPNAME {
            get {
                return this.zCPNAMEField;
            }
            set {
                this.zCPNAMEField = value;
                this.RaisePropertyChanged("ZCPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZCPMS {
            get {
                return this.zCPMSField;
            }
            set {
                this.zCPMSField = value;
                this.RaisePropertyChanged("ZCPMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZCPIDO {
            get {
                return this.zCPIDOField;
            }
            set {
                this.zCPIDOField = value;
                this.RaisePropertyChanged("ZCPIDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZCPSTATE {
            get {
                return this.zCPSTATEField;
            }
            set {
                this.zCPSTATEField = value;
                this.RaisePropertyChanged("ZCPSTATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal ZCPVALUE {
            get {
                return this.zCPVALUEField;
            }
            set {
                this.zCPVALUEField = value;
                this.RaisePropertyChanged("ZCPVALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZCPSTA {
            get {
                return this.zCPSTAField;
            }
            set {
                this.zCPSTAField = value;
                this.RaisePropertyChanged("ZCPSTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZCPEND {
            get {
                return this.zCPENDField;
            }
            set {
                this.zCPENDField = value;
                this.RaisePropertyChanged("ZCPEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZCPCHANNEL {
            get {
                return this.zCPCHANNELField;
            }
            set {
                this.zCPCHANNELField = value;
                this.RaisePropertyChanged("ZCPCHANNEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZCPSTORE {
            get {
                return this.zCPSTOREField;
            }
            set {
                this.zCPSTOREField = value;
                this.RaisePropertyChanged("ZCPSTORE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZWMATNR {
            get {
                return this.zWMATNRField;
            }
            set {
                this.zWMATNRField = value;
                this.RaisePropertyChanged("ZWMATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZCPSERNR {
            get {
                return this.zCPSERNRField;
            }
            set {
                this.zCPSERNRField = value;
                this.RaisePropertyChanged("ZCPSERNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ZCPLOY {
            get {
                return this.zCPLOYField;
            }
            set {
                this.zCPLOYField = value;
                this.RaisePropertyChanged("ZCPLOY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal ZCPPRICE {
            get {
                return this.zCPPRICEField;
            }
            set {
                this.zCPPRICEField = value;
                this.RaisePropertyChanged("ZCPPRICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ZCPSCENE {
            get {
                return this.zCPSCENEField;
            }
            set {
                this.zCPSCENEField = value;
                this.RaisePropertyChanged("ZCPSCENE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ZCPMULTICK {
            get {
                return this.zCPMULTICKField;
            }
            set {
                this.zCPMULTICKField = value;
                this.RaisePropertyChanged("ZCPMULTICK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_LOY_WELFAREResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZST_LOY_WELFARE[] eT_LOY_WELFAREField;
        
        private ZST_COUPON_RETURN[] eT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_LOY_WELFARE[] ET_LOY_WELFARE {
            get {
                return this.eT_LOY_WELFAREField;
            }
            set {
                this.eT_LOY_WELFAREField = value;
                this.RaisePropertyChanged("ET_LOY_WELFARE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_COUPON_RETURN[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_LOY_WELFARERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARE Z_CRM_LOY_WELFARE;
        
        public Z_CRM_LOY_WELFARERequest() {
        }
        
        public Z_CRM_LOY_WELFARERequest(Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARE Z_CRM_LOY_WELFARE) {
            this.Z_CRM_LOY_WELFARE = Z_CRM_LOY_WELFARE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_LOY_WELFAREResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Hmj.WebApp.DicountService.Z_CRM_LOY_WELFAREResponse Z_CRM_LOY_WELFAREResponse;
        
        public Z_CRM_LOY_WELFAREResponse1() {
        }
        
        public Z_CRM_LOY_WELFAREResponse1(Hmj.WebApp.DicountService.Z_CRM_LOY_WELFAREResponse Z_CRM_LOY_WELFAREResponse) {
            this.Z_CRM_LOY_WELFAREResponse = Z_CRM_LOY_WELFAREResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_LOY_WELFAREChannel : Hmj.WebApp.DicountService.ZWS_LOY_WELFARE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_LOY_WELFAREClient : System.ServiceModel.ClientBase<Hmj.WebApp.DicountService.ZWS_LOY_WELFARE>, Hmj.WebApp.DicountService.ZWS_LOY_WELFARE {
        
        public ZWS_LOY_WELFAREClient() {
        }
        
        public ZWS_LOY_WELFAREClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_LOY_WELFAREClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_LOY_WELFAREClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_LOY_WELFAREClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hmj.WebApp.DicountService.Z_CRM_LOY_WELFAREResponse1 Hmj.WebApp.DicountService.ZWS_LOY_WELFARE.Z_CRM_LOY_WELFARE(Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARERequest request) {
            return base.Channel.Z_CRM_LOY_WELFARE(request);
        }
        
        public Hmj.WebApp.DicountService.Z_CRM_LOY_WELFAREResponse Z_CRM_LOY_WELFARE(Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARE Z_CRM_LOY_WELFARE1) {
            Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARERequest inValue = new Hmj.WebApp.DicountService.Z_CRM_LOY_WELFARERequest();
            inValue.Z_CRM_LOY_WELFARE = Z_CRM_LOY_WELFARE1;
            Hmj.WebApp.DicountService.Z_CRM_LOY_WELFAREResponse1 retVal = ((Hmj.WebApp.DicountService.ZWS_LOY_WELFARE)(this)).Z_CRM_LOY_WELFARE(inValue);
            return retVal.Z_CRM_LOY_WELFAREResponse;
        }
    }
}
