//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmj.WebApp.SelectOrderNew {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SelectOrderNew.ZWS_Z_LOY_BP_GETORDER")]
    public interface ZWS_Z_LOY_BP_GETORDER {
        
        // CODEGEN: 操作 Z_LOY_BP_GETORDER 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_Z_LOY_BP_GETORDER:Z_LOY_BP_GETORDERReq" +
            "uest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERResponse1 Z_LOY_BP_GETORDER(Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_LOY_BP_GETORDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_ZCREATED_AT_BEGINField;
        
        private string i_ZCREATED_AT_ENDField;
        
        private string i_ZORPField;
        
        private ZZRETURN2[] t_RETURNField;
        
        private ZZSCRMD_ORDER[] t_ZCRMD_ORDERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_ZCREATED_AT_BEGIN {
            get {
                return this.i_ZCREATED_AT_BEGINField;
            }
            set {
                this.i_ZCREATED_AT_BEGINField = value;
                this.RaisePropertyChanged("I_ZCREATED_AT_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_ZCREATED_AT_END {
            get {
                return this.i_ZCREATED_AT_ENDField;
            }
            set {
                this.i_ZCREATED_AT_ENDField = value;
                this.RaisePropertyChanged("I_ZCREATED_AT_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_ZORP {
            get {
                return this.i_ZORPField;
            }
            set {
                this.i_ZORPField = value;
                this.RaisePropertyChanged("I_ZORP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZRETURN2[] T_RETURN {
            get {
                return this.t_RETURNField;
            }
            set {
                this.t_RETURNField = value;
                this.RaisePropertyChanged("T_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZSCRMD_ORDER[] T_ZCRMD_ORDER {
            get {
                return this.t_ZCRMD_ORDERField;
            }
            set {
                this.t_ZCRMD_ORDERField = value;
                this.RaisePropertyChanged("T_ZCRMD_ORDER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZRETURN2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZSCRMD_ORDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zVBELNField;
        
        private string zORHANGField;
        
        private string zORVField;
        
        private string zAUARTField;
        
        private string zOREField;
        
        private string zORRField;
        
        private string zZBRDField;
        
        private string zMATNRField;
        
        private string zGJField;
        
        private string zORAField;
        
        private string zORIField;
        
        private string zOROField;
        
        private string zORPField;
        
        private string zORDTAField;
        
        private string zORGField;
        
        private string zORQField;
        
        private string zORPLField;
        
        private string zORPYLField;
        
        private string zORPPLField;
        
        private string zORWField;
        
        private string zSERNRField;
        
        private string zLSJField;
        
        private string zLSKField;
        
        private string zORJField;
        
        private string zORKField;
        
        private string zORLField;
        
        private string zORZField;
        
        private string zORXField;
        
        private string zORCField;
        
        private string zOEBField;
        
        private string zORUField;
        
        private string zORYField;
        
        private string zORNField;
        
        private string zCREATED_BYField;
        
        private string zCREATED_ATField;
        
        private string zCHANGED_ATField;
        
        private string zCHANGED_BYField;
        
        private string zPMSField;
        
        private string zORFAPField;
        
        private string zORBZField;
        
        private string zZPOSField;
        
        private string zZBZField;
        
        private string zZYEJIField;
        
        private string zZODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZVBELN {
            get {
                return this.zVBELNField;
            }
            set {
                this.zVBELNField = value;
                this.RaisePropertyChanged("ZVBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZORHANG {
            get {
                return this.zORHANGField;
            }
            set {
                this.zORHANGField = value;
                this.RaisePropertyChanged("ZORHANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZORV {
            get {
                return this.zORVField;
            }
            set {
                this.zORVField = value;
                this.RaisePropertyChanged("ZORV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZAUART {
            get {
                return this.zAUARTField;
            }
            set {
                this.zAUARTField = value;
                this.RaisePropertyChanged("ZAUART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZORE {
            get {
                return this.zOREField;
            }
            set {
                this.zOREField = value;
                this.RaisePropertyChanged("ZORE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZORR {
            get {
                return this.zORRField;
            }
            set {
                this.zORRField = value;
                this.RaisePropertyChanged("ZORR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZZBRD {
            get {
                return this.zZBRDField;
            }
            set {
                this.zZBRDField = value;
                this.RaisePropertyChanged("ZZBRD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZMATNR {
            get {
                return this.zMATNRField;
            }
            set {
                this.zMATNRField = value;
                this.RaisePropertyChanged("ZMATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZGJ {
            get {
                return this.zGJField;
            }
            set {
                this.zGJField = value;
                this.RaisePropertyChanged("ZGJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZORA {
            get {
                return this.zORAField;
            }
            set {
                this.zORAField = value;
                this.RaisePropertyChanged("ZORA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZORI {
            get {
                return this.zORIField;
            }
            set {
                this.zORIField = value;
                this.RaisePropertyChanged("ZORI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZORO {
            get {
                return this.zOROField;
            }
            set {
                this.zOROField = value;
                this.RaisePropertyChanged("ZORO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZORP {
            get {
                return this.zORPField;
            }
            set {
                this.zORPField = value;
                this.RaisePropertyChanged("ZORP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZORDTA {
            get {
                return this.zORDTAField;
            }
            set {
                this.zORDTAField = value;
                this.RaisePropertyChanged("ZORDTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ZORG {
            get {
                return this.zORGField;
            }
            set {
                this.zORGField = value;
                this.RaisePropertyChanged("ZORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ZORQ {
            get {
                return this.zORQField;
            }
            set {
                this.zORQField = value;
                this.RaisePropertyChanged("ZORQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ZORPL {
            get {
                return this.zORPLField;
            }
            set {
                this.zORPLField = value;
                this.RaisePropertyChanged("ZORPL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ZORPYL {
            get {
                return this.zORPYLField;
            }
            set {
                this.zORPYLField = value;
                this.RaisePropertyChanged("ZORPYL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ZORPPL {
            get {
                return this.zORPPLField;
            }
            set {
                this.zORPPLField = value;
                this.RaisePropertyChanged("ZORPPL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ZORW {
            get {
                return this.zORWField;
            }
            set {
                this.zORWField = value;
                this.RaisePropertyChanged("ZORW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ZSERNR {
            get {
                return this.zSERNRField;
            }
            set {
                this.zSERNRField = value;
                this.RaisePropertyChanged("ZSERNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ZLSJ {
            get {
                return this.zLSJField;
            }
            set {
                this.zLSJField = value;
                this.RaisePropertyChanged("ZLSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ZLSK {
            get {
                return this.zLSKField;
            }
            set {
                this.zLSKField = value;
                this.RaisePropertyChanged("ZLSK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string ZORJ {
            get {
                return this.zORJField;
            }
            set {
                this.zORJField = value;
                this.RaisePropertyChanged("ZORJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string ZORK {
            get {
                return this.zORKField;
            }
            set {
                this.zORKField = value;
                this.RaisePropertyChanged("ZORK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ZORL {
            get {
                return this.zORLField;
            }
            set {
                this.zORLField = value;
                this.RaisePropertyChanged("ZORL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ZORZ {
            get {
                return this.zORZField;
            }
            set {
                this.zORZField = value;
                this.RaisePropertyChanged("ZORZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ZORX {
            get {
                return this.zORXField;
            }
            set {
                this.zORXField = value;
                this.RaisePropertyChanged("ZORX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string ZORC {
            get {
                return this.zORCField;
            }
            set {
                this.zORCField = value;
                this.RaisePropertyChanged("ZORC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string ZOEB {
            get {
                return this.zOEBField;
            }
            set {
                this.zOEBField = value;
                this.RaisePropertyChanged("ZOEB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ZORU {
            get {
                return this.zORUField;
            }
            set {
                this.zORUField = value;
                this.RaisePropertyChanged("ZORU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ZORY {
            get {
                return this.zORYField;
            }
            set {
                this.zORYField = value;
                this.RaisePropertyChanged("ZORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string ZORN {
            get {
                return this.zORNField;
            }
            set {
                this.zORNField = value;
                this.RaisePropertyChanged("ZORN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string ZCREATED_BY {
            get {
                return this.zCREATED_BYField;
            }
            set {
                this.zCREATED_BYField = value;
                this.RaisePropertyChanged("ZCREATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string ZCREATED_AT {
            get {
                return this.zCREATED_ATField;
            }
            set {
                this.zCREATED_ATField = value;
                this.RaisePropertyChanged("ZCREATED_AT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string ZCHANGED_AT {
            get {
                return this.zCHANGED_ATField;
            }
            set {
                this.zCHANGED_ATField = value;
                this.RaisePropertyChanged("ZCHANGED_AT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string ZCHANGED_BY {
            get {
                return this.zCHANGED_BYField;
            }
            set {
                this.zCHANGED_BYField = value;
                this.RaisePropertyChanged("ZCHANGED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string ZPMS {
            get {
                return this.zPMSField;
            }
            set {
                this.zPMSField = value;
                this.RaisePropertyChanged("ZPMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string ZORFAP {
            get {
                return this.zORFAPField;
            }
            set {
                this.zORFAPField = value;
                this.RaisePropertyChanged("ZORFAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string ZORBZ {
            get {
                return this.zORBZField;
            }
            set {
                this.zORBZField = value;
                this.RaisePropertyChanged("ZORBZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string ZZPOS {
            get {
                return this.zZPOSField;
            }
            set {
                this.zZPOSField = value;
                this.RaisePropertyChanged("ZZPOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string ZZBZ {
            get {
                return this.zZBZField;
            }
            set {
                this.zZBZField = value;
                this.RaisePropertyChanged("ZZBZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string ZZYEJI {
            get {
                return this.zZYEJIField;
            }
            set {
                this.zZYEJIField = value;
                this.RaisePropertyChanged("ZZYEJI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string ZZODY {
            get {
                return this.zZODYField;
            }
            set {
                this.zZODYField = value;
                this.RaisePropertyChanged("ZZODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_LOY_BP_GETORDERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZZRETURN2[] t_RETURNField;
        
        private ZZSCRMD_ORDER[] t_ZCRMD_ORDERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZRETURN2[] T_RETURN {
            get {
                return this.t_RETURNField;
            }
            set {
                this.t_RETURNField = value;
                this.RaisePropertyChanged("T_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZSCRMD_ORDER[] T_ZCRMD_ORDER {
            get {
                return this.t_ZCRMD_ORDERField;
            }
            set {
                this.t_ZCRMD_ORDERField = value;
                this.RaisePropertyChanged("T_ZCRMD_ORDER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_LOY_BP_GETORDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDER Z_LOY_BP_GETORDER;
        
        public Z_LOY_BP_GETORDERRequest() {
        }
        
        public Z_LOY_BP_GETORDERRequest(Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDER Z_LOY_BP_GETORDER) {
            this.Z_LOY_BP_GETORDER = Z_LOY_BP_GETORDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_LOY_BP_GETORDERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERResponse Z_LOY_BP_GETORDERResponse;
        
        public Z_LOY_BP_GETORDERResponse1() {
        }
        
        public Z_LOY_BP_GETORDERResponse1(Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERResponse Z_LOY_BP_GETORDERResponse) {
            this.Z_LOY_BP_GETORDERResponse = Z_LOY_BP_GETORDERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_Z_LOY_BP_GETORDERChannel : Hmj.WebApp.SelectOrderNew.ZWS_Z_LOY_BP_GETORDER, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_Z_LOY_BP_GETORDERClient : System.ServiceModel.ClientBase<Hmj.WebApp.SelectOrderNew.ZWS_Z_LOY_BP_GETORDER>, Hmj.WebApp.SelectOrderNew.ZWS_Z_LOY_BP_GETORDER {
        
        public ZWS_Z_LOY_BP_GETORDERClient() {
        }
        
        public ZWS_Z_LOY_BP_GETORDERClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_Z_LOY_BP_GETORDERClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_Z_LOY_BP_GETORDERClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_Z_LOY_BP_GETORDERClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERResponse1 Hmj.WebApp.SelectOrderNew.ZWS_Z_LOY_BP_GETORDER.Z_LOY_BP_GETORDER(Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERRequest request) {
            return base.Channel.Z_LOY_BP_GETORDER(request);
        }
        
        public Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERResponse Z_LOY_BP_GETORDER(Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDER Z_LOY_BP_GETORDER1) {
            Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERRequest inValue = new Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERRequest();
            inValue.Z_LOY_BP_GETORDER = Z_LOY_BP_GETORDER1;
            Hmj.WebApp.SelectOrderNew.Z_LOY_BP_GETORDERResponse1 retVal = ((Hmj.WebApp.SelectOrderNew.ZWS_Z_LOY_BP_GETORDER)(this)).Z_LOY_BP_GETORDER(inValue);
            return retVal.Z_LOY_BP_GETORDERResponse;
        }
    }
}
