//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmj.WebApp.UpdateMemberNew {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="UpdateMemberNew.ZWS_Z_LOY_BP_CHANGE")]
    public interface ZWS_Z_LOY_BP_CHANGE {
        
        // CODEGEN: 操作 Z_LOY_BP_CHANGE 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_Z_LOY_BP_CHANGE:Z_LOY_BP_CHANGERequest" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGEResponse1 Z_LOY_BP_CHANGE(Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_LOY_BP_CHANGE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZZADDRESSDATA i_ADDRESSDATAField;
        
        private ZZCENTRAL i_CENTRALField;
        
        private ZZCENTRALDATAPERSON i_CENTRALDATAPERSONField;
        
        private ZZCUSTOMER01 i_CUSTOMER01Field;
        
        private ZZCUSTOMER02 i_CUSTOMER02Field;
        
        private ZZCUSTOMER03 i_CUSTOMER03Field;
        
        private ZZCUSTOMER04 i_CUSTOMER04Field;
        
        private ZZCUSTOMER05 i_CUSTOMER05Field;
        
        private ZZCUSTOMER06 i_CUSTOMER06Field;
        
        private ZZCUSTOMER07 i_CUSTOMER07Field;
        
        private string i_PARTNERField;
        
        private ZZE_MAILDATA[] t_E_MAILDATAField;
        
        private ZZRETURN2[] t_RETURNField;
        
        private ZZTELEFONDATA[] t_TELEFONDATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZZADDRESSDATA I_ADDRESSDATA {
            get {
                return this.i_ADDRESSDATAField;
            }
            set {
                this.i_ADDRESSDATAField = value;
                this.RaisePropertyChanged("I_ADDRESSDATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZZCENTRAL I_CENTRAL {
            get {
                return this.i_CENTRALField;
            }
            set {
                this.i_CENTRALField = value;
                this.RaisePropertyChanged("I_CENTRAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ZZCENTRALDATAPERSON I_CENTRALDATAPERSON {
            get {
                return this.i_CENTRALDATAPERSONField;
            }
            set {
                this.i_CENTRALDATAPERSONField = value;
                this.RaisePropertyChanged("I_CENTRALDATAPERSON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ZZCUSTOMER01 I_CUSTOMER01 {
            get {
                return this.i_CUSTOMER01Field;
            }
            set {
                this.i_CUSTOMER01Field = value;
                this.RaisePropertyChanged("I_CUSTOMER01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ZZCUSTOMER02 I_CUSTOMER02 {
            get {
                return this.i_CUSTOMER02Field;
            }
            set {
                this.i_CUSTOMER02Field = value;
                this.RaisePropertyChanged("I_CUSTOMER02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ZZCUSTOMER03 I_CUSTOMER03 {
            get {
                return this.i_CUSTOMER03Field;
            }
            set {
                this.i_CUSTOMER03Field = value;
                this.RaisePropertyChanged("I_CUSTOMER03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ZZCUSTOMER04 I_CUSTOMER04 {
            get {
                return this.i_CUSTOMER04Field;
            }
            set {
                this.i_CUSTOMER04Field = value;
                this.RaisePropertyChanged("I_CUSTOMER04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ZZCUSTOMER05 I_CUSTOMER05 {
            get {
                return this.i_CUSTOMER05Field;
            }
            set {
                this.i_CUSTOMER05Field = value;
                this.RaisePropertyChanged("I_CUSTOMER05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ZZCUSTOMER06 I_CUSTOMER06 {
            get {
                return this.i_CUSTOMER06Field;
            }
            set {
                this.i_CUSTOMER06Field = value;
                this.RaisePropertyChanged("I_CUSTOMER06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ZZCUSTOMER07 I_CUSTOMER07 {
            get {
                return this.i_CUSTOMER07Field;
            }
            set {
                this.i_CUSTOMER07Field = value;
                this.RaisePropertyChanged("I_CUSTOMER07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string I_PARTNER {
            get {
                return this.i_PARTNERField;
            }
            set {
                this.i_PARTNERField = value;
                this.RaisePropertyChanged("I_PARTNER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZE_MAILDATA[] T_E_MAILDATA {
            get {
                return this.t_E_MAILDATAField;
            }
            set {
                this.t_E_MAILDATAField = value;
                this.RaisePropertyChanged("T_E_MAILDATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZRETURN2[] T_RETURN {
            get {
                return this.t_RETURNField;
            }
            set {
                this.t_RETURNField = value;
                this.RaisePropertyChanged("T_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZTELEFONDATA[] T_TELEFONDATA {
            get {
                return this.t_TELEFONDATAField;
            }
            set {
                this.t_TELEFONDATAField = value;
                this.RaisePropertyChanged("T_TELEFONDATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZADDRESSDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cOUNTRYField;
        
        private string rEGIONField;
        
        private string cITYField;
        
        private string sTREETField;
        
        private string pOSTL_COD1Field;
        
        private string sTR_SUPPL1Field;
        
        private string sTR_SUPPL2Field;
        
        private string sTR_SUPPL3Field;
        
        private string lOCATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
                this.RaisePropertyChanged("COUNTRY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
                this.RaisePropertyChanged("REGION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
                this.RaisePropertyChanged("STREET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string POSTL_COD1 {
            get {
                return this.pOSTL_COD1Field;
            }
            set {
                this.pOSTL_COD1Field = value;
                this.RaisePropertyChanged("POSTL_COD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STR_SUPPL1 {
            get {
                return this.sTR_SUPPL1Field;
            }
            set {
                this.sTR_SUPPL1Field = value;
                this.RaisePropertyChanged("STR_SUPPL1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string STR_SUPPL2 {
            get {
                return this.sTR_SUPPL2Field;
            }
            set {
                this.sTR_SUPPL2Field = value;
                this.RaisePropertyChanged("STR_SUPPL2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string STR_SUPPL3 {
            get {
                return this.sTR_SUPPL3Field;
            }
            set {
                this.sTR_SUPPL3Field = value;
                this.RaisePropertyChanged("STR_SUPPL3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
                this.RaisePropertyChanged("LOCATION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZTELEFONDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tELEPHONEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TELEPHONE {
            get {
                return this.tELEPHONEField;
            }
            set {
                this.tELEPHONEField = value;
                this.RaisePropertyChanged("TELEPHONE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZRETURN2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZE_MAILDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_MAILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_MAIL {
            get {
                return this.e_MAILField;
            }
            set {
                this.e_MAILField = value;
                this.RaisePropertyChanged("E_MAIL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER07 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA45Field;
        
        private string zA46Field;
        
        private string zA47Field;
        
        private string zA48Field;
        
        private string zA49Field;
        
        private string zA50Field;
        
        private string zA51Field;
        
        private string zA52Field;
        
        private string zA53Field;
        
        private string zA54Field;
        
        private string zA55Field;
        
        private string zA56Field;
        
        private string zA57Field;
        
        private string zA58Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA45 {
            get {
                return this.zA45Field;
            }
            set {
                this.zA45Field = value;
                this.RaisePropertyChanged("ZA45");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA46 {
            get {
                return this.zA46Field;
            }
            set {
                this.zA46Field = value;
                this.RaisePropertyChanged("ZA46");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA47 {
            get {
                return this.zA47Field;
            }
            set {
                this.zA47Field = value;
                this.RaisePropertyChanged("ZA47");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA48 {
            get {
                return this.zA48Field;
            }
            set {
                this.zA48Field = value;
                this.RaisePropertyChanged("ZA48");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZA49 {
            get {
                return this.zA49Field;
            }
            set {
                this.zA49Field = value;
                this.RaisePropertyChanged("ZA49");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZA50 {
            get {
                return this.zA50Field;
            }
            set {
                this.zA50Field = value;
                this.RaisePropertyChanged("ZA50");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZA51 {
            get {
                return this.zA51Field;
            }
            set {
                this.zA51Field = value;
                this.RaisePropertyChanged("ZA51");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZA52 {
            get {
                return this.zA52Field;
            }
            set {
                this.zA52Field = value;
                this.RaisePropertyChanged("ZA52");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZA53 {
            get {
                return this.zA53Field;
            }
            set {
                this.zA53Field = value;
                this.RaisePropertyChanged("ZA53");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZA54 {
            get {
                return this.zA54Field;
            }
            set {
                this.zA54Field = value;
                this.RaisePropertyChanged("ZA54");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZA55 {
            get {
                return this.zA55Field;
            }
            set {
                this.zA55Field = value;
                this.RaisePropertyChanged("ZA55");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZA56 {
            get {
                return this.zA56Field;
            }
            set {
                this.zA56Field = value;
                this.RaisePropertyChanged("ZA56");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZA57 {
            get {
                return this.zA57Field;
            }
            set {
                this.zA57Field = value;
                this.RaisePropertyChanged("ZA57");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZA58 {
            get {
                return this.zA58Field;
            }
            set {
                this.zA58Field = value;
                this.RaisePropertyChanged("ZA58");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER06 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA39Field;
        
        private string zA40Field;
        
        private string zA41Field;
        
        private string zA42Field;
        
        private string zA43Field;
        
        private string zA44Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA39 {
            get {
                return this.zA39Field;
            }
            set {
                this.zA39Field = value;
                this.RaisePropertyChanged("ZA39");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA40 {
            get {
                return this.zA40Field;
            }
            set {
                this.zA40Field = value;
                this.RaisePropertyChanged("ZA40");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA41 {
            get {
                return this.zA41Field;
            }
            set {
                this.zA41Field = value;
                this.RaisePropertyChanged("ZA41");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA42 {
            get {
                return this.zA42Field;
            }
            set {
                this.zA42Field = value;
                this.RaisePropertyChanged("ZA42");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZA43 {
            get {
                return this.zA43Field;
            }
            set {
                this.zA43Field = value;
                this.RaisePropertyChanged("ZA43");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZA44 {
            get {
                return this.zA44Field;
            }
            set {
                this.zA44Field = value;
                this.RaisePropertyChanged("ZA44");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER05 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA35Field;
        
        private string zA36Field;
        
        private string zA37Field;
        
        private string zA38Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA35 {
            get {
                return this.zA35Field;
            }
            set {
                this.zA35Field = value;
                this.RaisePropertyChanged("ZA35");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA36 {
            get {
                return this.zA36Field;
            }
            set {
                this.zA36Field = value;
                this.RaisePropertyChanged("ZA36");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA37 {
            get {
                return this.zA37Field;
            }
            set {
                this.zA37Field = value;
                this.RaisePropertyChanged("ZA37");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA38 {
            get {
                return this.zA38Field;
            }
            set {
                this.zA38Field = value;
                this.RaisePropertyChanged("ZA38");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER04 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA26Field;
        
        private string zA27Field;
        
        private string zA28Field;
        
        private string zA29Field;
        
        private string zA30Field;
        
        private string zA31Field;
        
        private string zA32Field;
        
        private string zA33Field;
        
        private string zA34Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA26 {
            get {
                return this.zA26Field;
            }
            set {
                this.zA26Field = value;
                this.RaisePropertyChanged("ZA26");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA27 {
            get {
                return this.zA27Field;
            }
            set {
                this.zA27Field = value;
                this.RaisePropertyChanged("ZA27");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA28 {
            get {
                return this.zA28Field;
            }
            set {
                this.zA28Field = value;
                this.RaisePropertyChanged("ZA28");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA29 {
            get {
                return this.zA29Field;
            }
            set {
                this.zA29Field = value;
                this.RaisePropertyChanged("ZA29");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZA30 {
            get {
                return this.zA30Field;
            }
            set {
                this.zA30Field = value;
                this.RaisePropertyChanged("ZA30");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZA31 {
            get {
                return this.zA31Field;
            }
            set {
                this.zA31Field = value;
                this.RaisePropertyChanged("ZA31");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZA32 {
            get {
                return this.zA32Field;
            }
            set {
                this.zA32Field = value;
                this.RaisePropertyChanged("ZA32");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZA33 {
            get {
                return this.zA33Field;
            }
            set {
                this.zA33Field = value;
                this.RaisePropertyChanged("ZA33");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZA34 {
            get {
                return this.zA34Field;
            }
            set {
                this.zA34Field = value;
                this.RaisePropertyChanged("ZA34");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER03 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA15Field;
        
        private string zA16Field;
        
        private string zA17Field;
        
        private string zA18Field;
        
        private string zA19Field;
        
        private string zA20Field;
        
        private string zA21Field;
        
        private string zA22Field;
        
        private string zA23Field;
        
        private string zA24Field;
        
        private string zA25Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA15 {
            get {
                return this.zA15Field;
            }
            set {
                this.zA15Field = value;
                this.RaisePropertyChanged("ZA15");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA16 {
            get {
                return this.zA16Field;
            }
            set {
                this.zA16Field = value;
                this.RaisePropertyChanged("ZA16");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA17 {
            get {
                return this.zA17Field;
            }
            set {
                this.zA17Field = value;
                this.RaisePropertyChanged("ZA17");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA18 {
            get {
                return this.zA18Field;
            }
            set {
                this.zA18Field = value;
                this.RaisePropertyChanged("ZA18");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZA19 {
            get {
                return this.zA19Field;
            }
            set {
                this.zA19Field = value;
                this.RaisePropertyChanged("ZA19");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZA20 {
            get {
                return this.zA20Field;
            }
            set {
                this.zA20Field = value;
                this.RaisePropertyChanged("ZA20");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZA21 {
            get {
                return this.zA21Field;
            }
            set {
                this.zA21Field = value;
                this.RaisePropertyChanged("ZA21");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZA22 {
            get {
                return this.zA22Field;
            }
            set {
                this.zA22Field = value;
                this.RaisePropertyChanged("ZA22");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZA23 {
            get {
                return this.zA23Field;
            }
            set {
                this.zA23Field = value;
                this.RaisePropertyChanged("ZA23");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZA24 {
            get {
                return this.zA24Field;
            }
            set {
                this.zA24Field = value;
                this.RaisePropertyChanged("ZA24");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZA25 {
            get {
                return this.zA25Field;
            }
            set {
                this.zA25Field = value;
                this.RaisePropertyChanged("ZA25");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER02 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA11Field;
        
        private string zA12Field;
        
        private string zA13Field;
        
        private string zA14Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA11 {
            get {
                return this.zA11Field;
            }
            set {
                this.zA11Field = value;
                this.RaisePropertyChanged("ZA11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA12 {
            get {
                return this.zA12Field;
            }
            set {
                this.zA12Field = value;
                this.RaisePropertyChanged("ZA12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA13 {
            get {
                return this.zA13Field;
            }
            set {
                this.zA13Field = value;
                this.RaisePropertyChanged("ZA13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA14 {
            get {
                return this.zA14Field;
            }
            set {
                this.zA14Field = value;
                this.RaisePropertyChanged("ZA14");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCUSTOMER01 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zA01Field;
        
        private string zA02Field;
        
        private string zA03Field;
        
        private string zA04Field;
        
        private string zA05Field;
        
        private string zA06Field;
        
        private string zA07Field;
        
        private string zA08Field;
        
        private string zA09Field;
        
        private string zA10Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZA01 {
            get {
                return this.zA01Field;
            }
            set {
                this.zA01Field = value;
                this.RaisePropertyChanged("ZA01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZA02 {
            get {
                return this.zA02Field;
            }
            set {
                this.zA02Field = value;
                this.RaisePropertyChanged("ZA02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZA03 {
            get {
                return this.zA03Field;
            }
            set {
                this.zA03Field = value;
                this.RaisePropertyChanged("ZA03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZA04 {
            get {
                return this.zA04Field;
            }
            set {
                this.zA04Field = value;
                this.RaisePropertyChanged("ZA04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZA05 {
            get {
                return this.zA05Field;
            }
            set {
                this.zA05Field = value;
                this.RaisePropertyChanged("ZA05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZA06 {
            get {
                return this.zA06Field;
            }
            set {
                this.zA06Field = value;
                this.RaisePropertyChanged("ZA06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZA07 {
            get {
                return this.zA07Field;
            }
            set {
                this.zA07Field = value;
                this.RaisePropertyChanged("ZA07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZA08 {
            get {
                return this.zA08Field;
            }
            set {
                this.zA08Field = value;
                this.RaisePropertyChanged("ZA08");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZA09 {
            get {
                return this.zA09Field;
            }
            set {
                this.zA09Field = value;
                this.RaisePropertyChanged("ZA09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZA10 {
            get {
                return this.zA10Field;
            }
            set {
                this.zA10Field = value;
                this.RaisePropertyChanged("ZA10");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCENTRALDATAPERSON : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lASTNAMEField;
        
        private string bIRTHDATEField;
        
        private string pREFIX1Field;
        
        private string bIRTHPLACEField;
        
        private string mARITALSTATUSField;
        
        private string tITLE_ACA1Field;
        
        private string tITLE_ACA2Field;
        
        private string tITLE_SPPLField;
        
        private string bIRTHNAMEField;
        
        private string fIRSTNAMEField;
        
        private string oCCUPATIONField;
        
        private string mIDDLENAMEField;
        
        private string sECONDNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LASTNAME {
            get {
                return this.lASTNAMEField;
            }
            set {
                this.lASTNAMEField = value;
                this.RaisePropertyChanged("LASTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BIRTHDATE {
            get {
                return this.bIRTHDATEField;
            }
            set {
                this.bIRTHDATEField = value;
                this.RaisePropertyChanged("BIRTHDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PREFIX1 {
            get {
                return this.pREFIX1Field;
            }
            set {
                this.pREFIX1Field = value;
                this.RaisePropertyChanged("PREFIX1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BIRTHPLACE {
            get {
                return this.bIRTHPLACEField;
            }
            set {
                this.bIRTHPLACEField = value;
                this.RaisePropertyChanged("BIRTHPLACE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MARITALSTATUS {
            get {
                return this.mARITALSTATUSField;
            }
            set {
                this.mARITALSTATUSField = value;
                this.RaisePropertyChanged("MARITALSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TITLE_ACA1 {
            get {
                return this.tITLE_ACA1Field;
            }
            set {
                this.tITLE_ACA1Field = value;
                this.RaisePropertyChanged("TITLE_ACA1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TITLE_ACA2 {
            get {
                return this.tITLE_ACA2Field;
            }
            set {
                this.tITLE_ACA2Field = value;
                this.RaisePropertyChanged("TITLE_ACA2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TITLE_SPPL {
            get {
                return this.tITLE_SPPLField;
            }
            set {
                this.tITLE_SPPLField = value;
                this.RaisePropertyChanged("TITLE_SPPL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BIRTHNAME {
            get {
                return this.bIRTHNAMEField;
            }
            set {
                this.bIRTHNAMEField = value;
                this.RaisePropertyChanged("BIRTHNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FIRSTNAME {
            get {
                return this.fIRSTNAMEField;
            }
            set {
                this.fIRSTNAMEField = value;
                this.RaisePropertyChanged("FIRSTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string OCCUPATION {
            get {
                return this.oCCUPATIONField;
            }
            set {
                this.oCCUPATIONField = value;
                this.RaisePropertyChanged("OCCUPATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string MIDDLENAME {
            get {
                return this.mIDDLENAMEField;
            }
            set {
                this.mIDDLENAMEField = value;
                this.RaisePropertyChanged("MIDDLENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string SECONDNAME {
            get {
                return this.sECONDNAMEField;
            }
            set {
                this.sECONDNAMEField = value;
                this.RaisePropertyChanged("SECONDNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZCENTRAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tITLE_KEYField;
        
        private string sEARCHTERM1Field;
        
        private string sEARCHTERM2Field;
        
        private string tITLELETTERField;
        
        private string dATAORIGINTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TITLE_KEY {
            get {
                return this.tITLE_KEYField;
            }
            set {
                this.tITLE_KEYField = value;
                this.RaisePropertyChanged("TITLE_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SEARCHTERM1 {
            get {
                return this.sEARCHTERM1Field;
            }
            set {
                this.sEARCHTERM1Field = value;
                this.RaisePropertyChanged("SEARCHTERM1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SEARCHTERM2 {
            get {
                return this.sEARCHTERM2Field;
            }
            set {
                this.sEARCHTERM2Field = value;
                this.RaisePropertyChanged("SEARCHTERM2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TITLELETTER {
            get {
                return this.tITLELETTERField;
            }
            set {
                this.tITLELETTERField = value;
                this.RaisePropertyChanged("TITLELETTER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DATAORIGINTYPE {
            get {
                return this.dATAORIGINTYPEField;
            }
            set {
                this.dATAORIGINTYPEField = value;
                this.RaisePropertyChanged("DATAORIGINTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_LOY_BP_CHANGEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZZE_MAILDATA[] t_E_MAILDATAField;
        
        private ZZRETURN2[] t_RETURNField;
        
        private ZZTELEFONDATA[] t_TELEFONDATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZE_MAILDATA[] T_E_MAILDATA {
            get {
                return this.t_E_MAILDATAField;
            }
            set {
                this.t_E_MAILDATAField = value;
                this.RaisePropertyChanged("T_E_MAILDATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZRETURN2[] T_RETURN {
            get {
                return this.t_RETURNField;
            }
            set {
                this.t_RETURNField = value;
                this.RaisePropertyChanged("T_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZTELEFONDATA[] T_TELEFONDATA {
            get {
                return this.t_TELEFONDATAField;
            }
            set {
                this.t_TELEFONDATAField = value;
                this.RaisePropertyChanged("T_TELEFONDATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_LOY_BP_CHANGERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGE Z_LOY_BP_CHANGE;
        
        public Z_LOY_BP_CHANGERequest() {
        }
        
        public Z_LOY_BP_CHANGERequest(Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGE Z_LOY_BP_CHANGE) {
            this.Z_LOY_BP_CHANGE = Z_LOY_BP_CHANGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_LOY_BP_CHANGEResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGEResponse Z_LOY_BP_CHANGEResponse;
        
        public Z_LOY_BP_CHANGEResponse1() {
        }
        
        public Z_LOY_BP_CHANGEResponse1(Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGEResponse Z_LOY_BP_CHANGEResponse) {
            this.Z_LOY_BP_CHANGEResponse = Z_LOY_BP_CHANGEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_Z_LOY_BP_CHANGEChannel : Hmj.WebApp.UpdateMemberNew.ZWS_Z_LOY_BP_CHANGE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_Z_LOY_BP_CHANGEClient : System.ServiceModel.ClientBase<Hmj.WebApp.UpdateMemberNew.ZWS_Z_LOY_BP_CHANGE>, Hmj.WebApp.UpdateMemberNew.ZWS_Z_LOY_BP_CHANGE {
        
        public ZWS_Z_LOY_BP_CHANGEClient() {
        }
        
        public ZWS_Z_LOY_BP_CHANGEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_Z_LOY_BP_CHANGEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_Z_LOY_BP_CHANGEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_Z_LOY_BP_CHANGEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGEResponse1 Hmj.WebApp.UpdateMemberNew.ZWS_Z_LOY_BP_CHANGE.Z_LOY_BP_CHANGE(Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGERequest request) {
            return base.Channel.Z_LOY_BP_CHANGE(request);
        }
        
        public Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGEResponse Z_LOY_BP_CHANGE(Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGE Z_LOY_BP_CHANGE1) {
            Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGERequest inValue = new Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGERequest();
            inValue.Z_LOY_BP_CHANGE = Z_LOY_BP_CHANGE1;
            Hmj.WebApp.UpdateMemberNew.Z_LOY_BP_CHANGEResponse1 retVal = ((Hmj.WebApp.UpdateMemberNew.ZWS_Z_LOY_BP_CHANGE)(this)).Z_LOY_BP_CHANGE(inValue);
            return retVal.Z_LOY_BP_CHANGEResponse;
        }
    }
}
